name: diagram
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-48.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  diagram_editor: ^0.1.6 
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
